"""Per-instrument brief screen — fundamentals header, history charts, AI brief."""

from __future__ import annotations

from typing import ClassVar

from textual.app import ComposeResult
from textual.binding import BindingType
from textual.containers import VerticalScroll
from textual.screen import Screen
from textual.widgets import Footer, LoadingIndicator, Static

from openbourse.domain import AiBrief, Candidate, FundamentalsSnapshot
from openbourse.providers import Providers
from openbourse.tui.widgets import HistoryCharts


class BriefScreen(Screen[None]):
    """Per-instrument detail: fundamentals header, history charts, AI brief."""

    BINDINGS: ClassVar[list[BindingType]] = [
        ("escape", "app.pop_screen", "Back"),
        ("b", "app.pop_screen", "Back"),
        ("d", "download_history", "Download history"),
    ]

    def __init__(
        self,
        *,
        candidate: Candidate,
        providers: Providers,
        history: list[FundamentalsSnapshot] | None = None,
    ) -> None:
        super().__init__()
        self._candidate = candidate
        self._providers = providers
        self._history = history or []

    def compose(self) -> ComposeResult:
        """Render a full-width header, history charts, and the AI brief body."""
        from openbourse.tui.screens.screener import _truncate_summary

        c = self._candidate
        snap = c.snapshot
        price_str = f"${snap.price_usd:,.2f}" if snap.price_usd is not None else "—"
        header = (
            f"[b cyan]{c.instrument.ticker}[/b cyan]  {c.instrument.name}  "
            f"[dim]{c.instrument.sector or ''}  ·  "
            f"{c.instrument.exchange or ''}[/dim]\n"
            f"Price [b]{price_str}[/b]  ·  "
            f"Mkt cap [b]${snap.market_cap_usd / 1e9:.1f}B[/b]  ·  "
            f"Rev growth [b]{snap.revenue_growth_pct:+.1f}%[/b]  ·  "
            f"GM [b]{snap.gross_margin_pct:.1f}%[/b]  ·  "
            f"Net debt/EBITDA [b]{snap.net_debt_to_ebitda:.2f}x[/b]  ·  "
            f"FCF yld [b]{snap.fcf_yield_pct:.1f}%[/b]\n"
            f"Score [b]{c.score}[/b]    Verdict [b]{c.verdict.value}[/b]"
        )
        if c.instrument.business_summary:
            # The brief screen has more vertical room than the detail pane,
            # so we allow a longer truncation here.
            header += (
                "\n[dim italic]"
                + _truncate_summary(c.instrument.business_summary, max_chars=420)
                + "[/dim italic]"
            )
        yield Static(header, id="brief-header")
        # Always include the charts widget — it self-handles "insufficient
        # history" so even ad-hoc lookups with no history render gracefully.
        yield HistoryCharts(self._history)
        yield LoadingIndicator(id="brief-loading")
        yield VerticalScroll(Static("", id="brief-body"), id="brief-scroll")
        yield Footer()

    async def on_mount(self) -> None:
        """Kick off the brief-loading worker so the UI stays responsive."""
        self.run_worker(self._load_brief(), exclusive=True)

    async def _load_brief(self) -> None:
        """Fetch recent filings (best-effort) and the AI brief, then render."""
        from openbourse.providers.base import Filing

        c = self._candidate
        filings: list[Filing] = []
        if c.instrument.cik:
            try:
                filings = await self._providers.filings.recent_filings(c.instrument.cik, limit=3)
            except (OSError, ValueError):  # pragma: no cover - provider edge case
                filings = []
        brief = await self._providers.brief.write_brief(c.instrument, c.snapshot, filings)
        self._render_brief(brief)

    def _render_brief(self, brief: AiBrief) -> None:
        """Hide the loading indicator and write the brief body in place."""
        self.query_one("#brief-loading", LoadingIndicator).display = False
        body = self.query_one("#brief-body", Static)
        bullets = "\n".join(f"  • {b}" for b in brief.bullets)
        body.update(
            f"[b]Summary[/b]\n{brief.summary}\n\n"
            f"[b]Key points[/b]\n{bullets or '  • (no bullets)'}\n\n"
            f"[dim]Generated by {brief.model} at "
            f"{brief.generated_at:%Y-%m-%d %H:%M:%S} UTC[/dim]"
        )

    def action_download_history(self) -> None:
        """Pull annual history from the live provider, persist, and refresh charts.

        Useful when the brief landed with sparse charts because the ticker
        was looked up ad-hoc (or only its current snapshot was ingested).
        After download the chart panel is rebuilt in place — no need to
        leave and re-enter the brief.
        """
        self.run_worker(self._download_history_worker(), exclusive=False)

    async def _download_history_worker(self) -> None:
        """Worker body for :meth:`action_download_history`."""
        from openbourse.config import get_settings
        from openbourse.db.engine import create_engine_from_url, get_session_factory
        from openbourse.screening import TickerLookupError, lookup_with_history

        ticker = self._candidate.instrument.ticker
        self.app.notify(
            f"Fetching history for {ticker}…",
            title="History download",
            timeout=2,
        )
        engine = create_engine_from_url(get_settings().database_url)
        factory = get_session_factory(engine)
        try:
            async with factory() as session:
                _candidate, history = await lookup_with_history(
                    ticker, self._providers, session=session
                )
        except TickerLookupError as exc:
            self.app.notify(
                str(exc),
                title="Download failed",
                severity="error",
                timeout=6,
            )
            return
        except Exception as exc:  # surface any provider/db error to the user
            self.app.notify(
                f"{type(exc).__name__}: {exc}",
                title="Download failed",
                severity="error",
                timeout=6,
            )
            return
        finally:
            await engine.dispose()

        if not history:
            self.app.notify(
                f"{ticker} has no history available from the configured provider.",
                title="No history",
                severity="warning",
                timeout=4,
            )
            return

        self._history = list(history)
        # Swap the chart widget in place so the user sees populated charts
        # without having to back out and re-enter the brief.
        old = self.query_one(HistoryCharts)
        await old.remove()
        await self.mount(
            HistoryCharts(self._history),
            after=self.query_one("#brief-header"),
        )
        self.app.notify(
            f"Loaded {len(history)} history points for {ticker}.",
            title="Download complete",
            timeout=3,
        )
