"""Per-instrument brief screen — fundamentals header, history charts, AI brief."""

from __future__ import annotations

from datetime import date
from typing import ClassVar

from textual.app import ComposeResult
from textual.binding import BindingType
from textual.containers import VerticalScroll
from textual.screen import Screen
from textual.widgets import Footer, LoadingIndicator, Static

from openbourse.domain import (
    AiBrief,
    Candidate,
    FundamentalsSnapshot,
    ScreenDefinition,
)
from openbourse.providers import Providers
from openbourse.screening import compute_style_fit
from openbourse.tui.widgets import HistoryCharts, PriceChart

_CONCERN_GLYPHS = {
    "flagged": ("⚠", "yellow"),
    "clear": ("✓", "green"),
    "unknown": ("?", "dim"),
}


def _format_brief_body(brief: AiBrief) -> str:
    """Render an :class:`AiBrief` as a Rich-marked-up multi-section block.

    Sections are stacked vertically with colour-coded headers so the user
    can scan bull / bear / risks / concerns at a glance. Concerns render
    as a status-glyph + concern + note grid.
    """
    parts: list[str] = []
    if brief.summary:
        parts.append(f"[b]Summary[/b]\n{brief.summary}")

    if brief.bull:
        parts.append(_format_section("Bull case", brief.bull, color="green"))
    if brief.bear:
        parts.append(_format_section("Bear case", brief.bear, color="red"))
    if brief.risks:
        parts.append(_format_section("Risks to monitor", brief.risks, color="yellow"))

    if brief.concerns:
        max_concern_width = max(len(c.concern) for c in brief.concerns)
        rows: list[str] = []
        for finding in brief.concerns:
            glyph, color = _CONCERN_GLYPHS.get(finding.status, _CONCERN_GLYPHS["unknown"])
            note = f"  [dim]{finding.note}[/dim]" if finding.note else ""
            rows.append(
                f"  [{color}]{glyph}[/{color}] "
                f"{finding.concern.ljust(max_concern_width)}  "
                f"[{color}]{finding.status}[/{color}]{note}"
            )
        parts.append("[b]Concerns checked[/b]\n" + "\n".join(rows))

    parts.append(
        f"[dim]Generated by {brief.model} at "
        f"{brief.generated_at:%Y-%m-%d %H:%M:%S} UTC[/dim]"
    )
    return "\n\n".join(parts)


def _format_section(title: str, items: tuple[str, ...], *, color: str) -> str:
    """Format one bullet section with a coloured header."""
    bullets = "\n".join(f"  • {item}" for item in items)
    return f"[b {color}]{title}[/b {color}]\n{bullets}"


class BriefScreen(Screen[None]):
    """Per-instrument detail: fundamentals header, history charts, AI brief."""

    BINDINGS: ClassVar[list[BindingType]] = [
        ("escape", "app.pop_screen", "Back"),
        ("b", "app.pop_screen", "Back"),
        ("d", "download_history", "Download history"),
    ]

    def __init__(
        self,
        *,
        candidate: Candidate,
        providers: Providers,
        history: list[FundamentalsSnapshot] | None = None,
        screen: ScreenDefinition | None = None,
    ) -> None:
        super().__init__()
        self._candidate = candidate
        self._providers = providers
        self._history = history or []
        # The active screen is used to compute the style-fit %; a None
        # screen (e.g., from `bourse lookup`) skips that section.
        self._screen = screen

    def compose(self) -> ComposeResult:
        """Render a full-width header, history charts, and the AI brief body."""
        from openbourse.tui.screens.screener import _truncate_summary

        c = self._candidate
        snap = c.snapshot
        price_str = f"${snap.price_usd:,.2f}" if snap.price_usd is not None else "—"
        header = (
            f"[b cyan]{c.instrument.ticker}[/b cyan]  {c.instrument.name}  "
            f"[dim]{c.instrument.sector or ''}  ·  "
            f"{c.instrument.exchange or ''}[/dim]\n"
            f"Price [b]{price_str}[/b]  ·  "
            f"Mkt cap [b]${snap.market_cap_usd / 1e9:.1f}B[/b]  ·  "
            f"Rev growth [b]{snap.revenue_growth_pct:+.1f}%[/b]  ·  "
            f"GM [b]{snap.gross_margin_pct:.1f}%[/b]  ·  "
            f"Net debt/EBITDA [b]{snap.net_debt_to_ebitda:.2f}x[/b]  ·  "
            f"FCF yld [b]{snap.fcf_yield_pct:.1f}%[/b]\n"
            f"Score [b]{c.score}[/b]"
        )
        if self._screen is not None:
            fit_pct = compute_style_fit(snap, self._screen)
            header += f"    Style fit [b]{fit_pct:.0f}%[/b]"
        header += f"    Verdict [b]{c.verdict.value}[/b]"
        if c.instrument.business_summary:
            # The brief screen has more vertical room than the detail pane,
            # so we allow a longer truncation here.
            header += (
                "\n[dim italic]"
                + _truncate_summary(c.instrument.business_summary, max_chars=420)
                + "[/dim italic]"
            )
        yield Static(header, id="brief-header")
        # Wide price chart on top — most-requested visual when looking at a
        # ticker. Starts empty and is repopulated by the worker once
        # ``providers.fundamentals.price_history`` returns.
        yield PriceChart(c.instrument.ticker, [], chart_width=140)
        # 2x2 fundamentals trend grid below the price chart. Self-handles
        # "insufficient history" so ad-hoc lookups still render.
        yield HistoryCharts(self._history)
        yield LoadingIndicator(id="brief-loading")
        yield VerticalScroll(Static("", id="brief-body"), id="brief-scroll")
        yield Footer()

    async def on_mount(self) -> None:
        """Kick off the brief-loading worker so the UI stays responsive."""
        self.run_worker(self._load_brief(), exclusive=True)

    async def _load_brief(self) -> None:
        """Fetch filings, the AI brief, and 3y price history concurrently.

        Each provider call is independent; running them in ``asyncio.gather``
        means the brief screen renders as soon as the slowest of the three
        completes, not after their cumulative wall time.
        """
        import asyncio

        from openbourse.providers.base import Filing

        c = self._candidate

        async def _fetch_filings() -> list[Filing]:
            if not c.instrument.cik:
                return []
            try:
                return await self._providers.filings.recent_filings(c.instrument.cik, limit=3)
            except (OSError, ValueError):  # pragma: no cover - provider edge case
                return []

        async def _fetch_prices() -> list[tuple[date, float]]:
            try:
                return await self._providers.fundamentals.price_history(
                    c.instrument.ticker, period="3y", interval="1d"
                )
            except (OSError, ValueError):  # pragma: no cover - provider edge case
                return []

        filings, price_points = await asyncio.gather(_fetch_filings(), _fetch_prices())
        # The brief generator depends on filings, so it runs after them.
        brief = await self._providers.brief.write_brief(c.instrument, c.snapshot, filings)
        self._render_brief(brief)
        await self._render_price_chart(price_points)

    async def _render_price_chart(self, points: list[tuple[date, float]]) -> None:
        """Replace the empty placeholder PriceChart with one bound to ``points``."""
        old = self.query_one(PriceChart)
        await old.remove()
        await self.mount(
            PriceChart(self._candidate.instrument.ticker, points, chart_width=140),
            after=self.query_one("#brief-header"),
        )

    def _render_brief(self, brief: AiBrief) -> None:
        """Hide the loading indicator and paint the structured brief sections."""
        self.query_one("#brief-loading", LoadingIndicator).display = False
        body = self.query_one("#brief-body", Static)
        body.update(_format_brief_body(brief))

    def action_download_history(self) -> None:
        """Pull annual history from the live provider, persist, and refresh charts.

        Useful when the brief landed with sparse charts because the ticker
        was looked up ad-hoc (or only its current snapshot was ingested).
        After download the chart panel is rebuilt in place — no need to
        leave and re-enter the brief.
        """
        self.run_worker(self._download_history_worker(), exclusive=False)

    async def _download_history_worker(self) -> None:
        """Worker body for :meth:`action_download_history`."""
        from openbourse.config import get_settings
        from openbourse.db.engine import create_engine_from_url, get_session_factory
        from openbourse.screening import TickerLookupError, lookup_with_history

        ticker = self._candidate.instrument.ticker
        self.app.notify(
            f"Fetching history for {ticker}…",
            title="History download",
            timeout=2,
        )
        engine = create_engine_from_url(get_settings().database_url)
        factory = get_session_factory(engine)
        try:
            async with factory() as session:
                _candidate, history = await lookup_with_history(
                    ticker, self._providers, session=session
                )
        except TickerLookupError as exc:
            self.app.notify(
                str(exc),
                title="Download failed",
                severity="error",
                timeout=6,
            )
            return
        except Exception as exc:  # surface any provider/db error to the user
            self.app.notify(
                f"{type(exc).__name__}: {exc}",
                title="Download failed",
                severity="error",
                timeout=6,
            )
            return
        finally:
            await engine.dispose()

        if not history:
            self.app.notify(
                f"{ticker} has no history available from the configured provider.",
                title="No history",
                severity="warning",
                timeout=4,
            )
            return

        self._history = list(history)
        # Swap the chart widget in place so the user sees populated charts
        # without having to back out and re-enter the brief.
        old = self.query_one(HistoryCharts)
        await old.remove()
        await self.mount(
            HistoryCharts(self._history),
            after=self.query_one("#brief-header"),
        )
        self.app.notify(
            f"Loaded {len(history)} history points for {ticker}.",
            title="Download complete",
            timeout=3,
        )
